<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\ChaosDotNet\ChaosDotNet.csproj" />
    <ProjectReference Include="..\..\src\ChaosDotNet.Sql\ChaosDotNet.Sql.csproj" />
    <ProjectReference Include="..\..\src\ChaosDotNet.SqlServer\ChaosDotNet.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\ChaosDotNet.Npgsql\ChaosDotNet.Npgsql.csproj" />
    <ProjectReference Include="..\..\src\ChaosDotNet.EntityFrameworkCore\ChaosDotNet.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\ChaosDotNet.Redis\ChaosDotNet.Redis.csproj" />
    <ProjectReference Include="..\..\src\ChaosDotNet.Caching\ChaosDotNet.Caching.csproj" />
    <ProjectReference Include="..\..\src\ChaosDotNet.AzureServiceBus\ChaosDotNet.AzureServiceBus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Data.SqlClient" VersionOverride="7.1.0" />
    <PackageReference Include="Npgsql" VersionOverride="10.0.3" />
    <PackageReference Include="StackExchange.Redis" VersionOverride="3.3.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>

</Project>
